src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="recived")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;




    public function __construct()
    {
     $this->created_at = new \DateTime();   
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?Users
    {
        return $this->sender;
    }

    public function setSender(?Users $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?Users
    {
        return $this->recipient;
    }

    public function setRecipient(?Users $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Users;
use App\Entity\Messages;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('title', TextType::class, [
            "attr" => [
                "class" => "form-control"
            ]
        ])
        ->add('message', TextareaType::class, [
            "attr" => [
                "class" => "form-control"
            ]
        ])
        ->add('recipient', EntityType::class, [
            "class" => Users::class,
            "choice_label" => "email",
            "attr" => [
                "class" => "select2"
            ]
        ])
        ->add('envoyer', SubmitType::class, [
            "attr" => [
                "class" => "btn btn-outline-dark"
            ]
        ])
        ;
    }



    
  
 

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessageType;
use Symfony\Component\HttpFoundation\Request;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MessageController extends AbstractController
{
    /**
     * @Route("/message", name="app_message")
     */
    public function index(): Response
    {
        return $this->render('message/index.html.twig', [
            'controller_name' => 'MessageController',
        ]);
    }



      /**
     * @Route("/send", name="app_send")
     */
    public function send(Request $request, FlashyNotifier $flashyNotifier): Response
    {
        $message = new Messages;
        $form = $this->createForm(MessageType::class, $message);
        
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $message->setSender($this->getUser());

            $em = $this->getDoctrine()->getManager();
            $em->persist($message);
            $em->flush();

            $this->addFlash("message", "Message envoyé avec succès.");
            return $this->redirectToRoute("app_message");

           // $flashyNotifier->success('Message envoyé avec succé');

        }

        return $this->render("message/send.html.twig", [
            "form" => $form->createView()
        ]);
    }


       /**
     * @Route("/received", name="app_received")
     */
    public function received(): Response
    {
        return $this->render('message/received.html.twig');
    }





      /**
     * @Route("/read/{id}", name="app_read")
     */
    public function read(Messages $message): Response
    {
        $message->setIsRead(true);
        $em = $this->getDoctrine()->getManager();
        $em->persist($message);
        $em->flush();

        return $this->render('message/read.html.twig', compact("message"));
    }

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(Messages $message): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($message);
        $em->flush();

        return $this->redirectToRoute("app_recived");
    }




        /**
     * @Route("/sent", name="app_sent")
     */
    public function sent(): Response
    {
        return $this->render('message/sent.html.twig');
    }

}

templates/message/index.html.twig
<html>
 <title>{% block title %}Messages{% endblock %}</title>
    {% block stylesheets %}
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    {% endblock %}
<html>


      {% for message in app.flashes("message") %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}


{% block body %}
<section class="container">
		<div class="row">
			<div class="col">
				<h1>Messagerie</h1>
				<p>Résumé de la messagerie</p>
				<p>Reçus : {{ app.user.recived|length}}</p>
				<p>Envoyés : {{ app.user.sent|length}}</p>
				<a class="btn btn-outline-dark" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Menu
				</a>
                <a href="{{ path('app_send')}}" class="btn btn-outline-dark">Envoyer un message</a>
			</div>
		</div>
	</section>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
            <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action active">Accueil</a>
            </div>
            <div class="list-group">
                <a href="{{ path('app_received')}}" class="list-group-item list-group-item-action">Boîte de réception</a>

            </div>
            <div class="list-group">
                <a href="{{ path('app_sent')}}" class="list-group-item list-group-item-action">Eléments envoyés</a>
            </div>
            <div class="list-group">
                <a href="{{ path('app_home')}}" class="list-group-item list-group-item-action">Home</a>
                
            </div>
		</div>
	</div>
{% endblock %}

</html>

   {% block javascripts %}



     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous" defer></script>

{% endblock %}


</html>

templates/message/read.html.twig
<html>
 <title>{% block title %}Message{% endblock %}</title>


  {% block stylesheets %}
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        
    {% endblock %}

<body style="background-color : #007bff">


{% block body %}
	<section class="container" style="margin-top : 200px">
		<div class="row">
			<div class="col-12">
				<h1>Messagerie</h1>
                <h2>{{ message.title }}</h2>
                <p>Message de {{ message.sender.email }}</p>
                <p>Le {{ message.createdAt|date }}</p>
                <div>{{ message.message }}</div>
				<a class="btn btn-outline-dark" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Menu
				</a>
                <a href="{{ path('app_received')}}" class="btn btn-outline-dark">Retour à la boite de réception</a>
			</div>
		</div>
	</section>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
            <div class="list-group">
                <a href="{{path("app_message")}}" class="list-group-item list-group-item-action">Accueil</a>
            </div>
            <div class="list-group">
                <a href="{{ path('app_received')}}" class="list-group-item list-group-item-action active">Boîte de réception</a>
            </div>
            <div class="list-group">
                <a href="{{ path('app_sent')}}" class="list-group-item list-group-item-action">Eléments envoyés</a>
            </div>
             <div class="list-group">
                <a href="{{ path('app_home')}}" class="list-group-item list-group-item-action">Home</a>
                
            </div>
		</div>
	</div>
{% endblock %}


</body>
   {% block javascripts %}



     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous" defer></script>

 
        {% endblock %}   
     


</html>

templates/message/received.html.twig
<html>
 <title>{% block title %}Message{% endblock %}</title>


  {% block stylesheets %}
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        
    {% endblock %}

<body>


{% block body %}
	<section class="container" style="margin-top : 200px">
		<div class="row">
			<div class="col-12">
				<h1>Messagerie</h1>
				<h2>Boîte de réception</h2>
				<p>Vous avez reçu
					{{ app.user.recived|length }}
					messages</p>
			</div>
			<div class="col-3">De</div>
			<div class="col-3">Sujet</div>
			<div class="col-3">Date</div>
			<div class="col-3">Actions</div>
			{% for message in app.user.recived %}
				{% set bold = "" %}
				{% if message.isRead == 0 %}
					{% set bold = "fw-bold" %}
				{% endif %}

				<div class="col-3 {{bold}}">{{ message.sender.email }}</div>
				<div class="col-3 {{bold}}">
					<a href="{{ path("app_read", {id: message.id}) }}">{{ message.title }}</a>
				</div>
				<div class="col-3 {{bold}}">{{ message.createdAt|date }}</div>
				<div class="col-3">
                    <a href="{{ path("delete", {id: message.id}) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-excel-fill text-danger" viewbox="0 0 16 16">
                            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM5.884 4.68L8 7.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 8l2.233 2.68a.5.5 0 0 1-.768.64L8 8.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 8 5.116 5.32a.5.5 0 1 1 .768-.64z"/>
                        </svg>
                    </a>
				</div>
			{% endfor %}


			<div class="col">
				<a class="btn btn-outline-dark" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Menu
				</a>
				<a href="{{path("app_send")}}" class="btn btn-outline-dark">Envoyer un message</a>
			</div>
		</div>
	</section>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{path("app_message")}}" class="list-group-item list-group-item-action">Accueil</a>
			</div>
			<div class="list-group">
				<a href="{{ path('app_received')}}" class="list-group-item list-group-item-action active">Boîte de réception</a>
			</div>
			<div class="list-group">
				<a href="{{ path('app_sent')}}" class="list-group-item list-group-item-action">Eléments envoyés</a>
			</div>
			 <div class="list-group">
                <a href="{{ path('app_home')}}" class="list-group-item list-group-item-action">Home</a>
                
            </div>
		</div>
	</div>
{% endblock %}
</body>
   {% block javascripts %}



     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous" defer></script>

 
        {% endblock %}   
     


</html>

templates/message/send.html.twig
<html>
 <title>{% block title %}Envoyer messages{% endblock %}</title>


  {% block stylesheets %}
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

	     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.6.95/css/materialdesignicons.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"> 

  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />


    {% endblock %}

<body>


    


{% block body %}

    
	<section class="container" style="margin-top : 200px;">
		<div class="row">
			<div class="col">
				<h1>Envoyer un message</h1>
                {{ form(form) }}
				<a class="btn btn-outline-dark" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Menu
				</a>
			</div>
		</div>
	</section>

	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
            <div class="list-group">
                <a href="{{path("app_message")}}" class="list-group-item list-group-item-action">Accueil</a>
            </div>
            <div class="list-group">
                <a href="{{ path('app_received')}}" class="list-group-item list-group-item-action">Boîte de réception</a>
            </div>
            <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action">Eléments envoyés</a>
            </div>
             <div class="list-group">
                <a href="{{ path('app_home')}}" class="list-group-item list-group-item-action">Home</a>
                
            </div>
		</div>
	</div>
{% endblock %}

</body>


   {% block javascripts %}



     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous" defer></script>

	    <script src="{{asset("assets/js/jquery-3.3.1.min.js")}}"></script>
  <script src="{{asset("assets/js/jquery-migrate-3.0.1.min.js")}}"></script>
  <script src="{{asset("assets/js/jquery-ui.js")}}"></script>
  <script src="{{asset("assets/js/popper.min.js")}}"></script>
  <script src="{{asset("assets/js/bootstrap.min.js")}}"></script>
  <script src="{{asset("assets/js/owl.carousel.min.js")}}"></script>
  <script src="{{asset("assets/js/jquery.stellar.min.js")}}"></script>
  <script src="{{asset("assets/js/jquery.countdown.min.js")}}"></script>
  <script src="{{asset("assets/js/bootstrap-datepicker.min.js")}}"></script>
  <script src="{{asset("assets/js/jquery.easing.1.3.js")}}"></script>
  <script src="{{asset("assets/js/aos.js")}}"></script>
  <script src="{{asset("assets/js/jquery.fancybox.min.js")}}"></script>
  <script src="{{asset("assets/js/jquery.sticky.js")}}"></script>
  <script src="{{asset("assets/js/jquery.mb.YTPlayer.min.js")}}"></script>


  <script src="{{asset("assets/js/main.js")}}"></script>

   <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    
    <script>
    
    $(document).ready(function() {
    $('.select2').select2();
        });

    </script>

        {% endblock %}   
     


</html>

templates/message/sent.html.twig
<html>
 <title>{% block title %}Message{% endblock %}</title>


  {% block stylesheets %}
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        
    {% endblock %}

<body >


{% block body %}
	<section class="container" style="margin-top : 200px">
		<div class="row">
			<div class="col-12">
				<h1>Messagerie</h1>
				<h2>Eléments envoyés</h2>
				<p>Vous avez envoyé
					{{ app.user.sent|length }}
					messages</p>
			</div>
			<div class="col-3">De</div>
			<div class="col-3">Sujet</div>
			<div class="col-3">Date</div>
			<div class="col-3">Actions</div>
			{% for message in app.user.sent %}
				{% set bold = "" %}
				{% if message.isRead == 0 %}
					{% set bold = "fw-bold" %}
				{% endif %}

				<div class="col-3 {{bold}}">{{ message.sender.email }}</div>
				<div class="col-3 {{bold}}">
					<a href="{{ path("app_read", {id: message.id}) }}">{{ message.title }}</a>
				</div>
				<div class="col-3 {{bold}}">{{ message.createdAt|date }}</div>
				<div class="col-3">
                    <a href="{{ path("delete", {id: message.id}) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-excel-fill text-danger" viewbox="0 0 16 16">
                            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM5.884 4.68L8 7.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 8l2.233 2.68a.5.5 0 0 1-.768.64L8 8.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 8 5.116 5.32a.5.5 0 1 1 .768-.64z"/>
                        </svg>
                    </a>
				</div>
			{% endfor %}


			<div class="col">
				<a class="btn btn-outline-dark" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Menu
				</a>
				<a href="{{path("app_send")}}" class="btn btn-outline-dark">Envoyer un message</a>
			</div>
		</div>
	</section>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("app_message") }}" class="list-group-item list-group-item-action">Accueil</a>
			</div>
			<div class="list-group">
				<a href="{{ path("app_received") }}" class="list-group-item list-group-item-action">Boîte de réception</a>
			</div>
			<div class="list-group">
				<a href="{{ path("app_sent") }}" class="list-group-item list-group-item-action active">Eléments envoyés</a>
			</div>
			 <div class="list-group">
                <a href="{{ path('app_home')}}" class="list-group-item list-group-item-action">Home</a>
                
            </div>
		</div>
	</div>
{% endblock %}

</body>

   {% block javascripts %}



     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous" defer></script>

 
        {% endblock %}   
     


</html>