src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups; 



/**
 * Article
 *
 * @ORM\Table(name="article", indexes={@ORM\Index(name="fk_article_user", columns={"user_id"})})
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 
 */
class Article
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @Groups("post:read")
     */
    private $id;

    /**
     * @var string
     * @Assert\NotBlank(message=" titre doit etre non vide")
     * @Assert\Length(
     *      min = 5,
     *      minMessage=" Entrer un titre au mini de 5 caracteres"
     *
     *     )
     * @ORM\Column(name="titre", type="string", length=30, nullable=false)
     * @Groups("post:read")
     */
    private $titre;

    /**
     * @var string
     * @Assert\NotBlank(message="description  doit etre non vide")
     * @Assert\Length(
     *      min = 7,
     *      max = 100,
     *      minMessage = "doit etre >=7 ",
     *      maxMessage = "doit etre <=100" )
     * @ORM\Column(name="description", type="text", length=65535, nullable=false)
     * @Groups("post:read")
     */
    private $description;

    /**
     * @var \Users
     *
     * @ORM\ManyToOne(targetEntity="Users")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * })
     */
    private $user;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=300, nullable=false)
     * Assert\NoBlank(message="Please upload image")
     * Assert\File(mimeTypes={"image/jpeg"})
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="article")
     */
    private $comment;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $Date;


    public function __construct()
    {
        $this->comment = new ArrayCollection();
        $this->Date = new \DateTime('now');
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser()
    
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Review $comment): self
    {
        if (!$this->comment->contains($comment)) {
            $this->comment[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Review $comment): self
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(?\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }





}

src/Form/ArticleType.php
<?php

    namespace App\Form;

    use App\Entity\Article;
    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\Extension\Core\Type\FileType;
    use Symfony\Component\Form\Extension\Core\Type\SubmitType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\OptionsResolver\OptionsResolver;

    class ArticleType extends AbstractType
    {
        public function buildForm(FormBuilderInterface $builder, array $options): void
        {
            $builder
                ->add('titre')
                ->add('description')
                ->add('image',FileType::class , [
                'label'=> false,
                'multiple'=>true,
                'mapped'=> false,
                'required'=>false])
                ->add('ajouter',SubmitType::class)

            ;
        }

        public function configureOptions(OptionsResolver $resolver): void
        {
            $resolver->setDefaults([
                'data_class' => Article::class,
            ]);
        }
    }

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use Dompdf\Dompdf;
use Dompdf\Options;
use App\Entity\Review;
use App\Entity\Article;
use Twilio\Rest\Client;
use App\Form\ReviewType;
use App\Form\SearchType;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use mofodojodino\ProfanityFilter\Check;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArticleController extends AbstractController
{
    private $twilio;

    public function __construct(Client $twilio)
    {
        $this->twilio = $twilio;
    }
    
    /**
     * @Route("/app_article", name="app_article")
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'controller_name' => 'ArticleController',
        ]);
    }

    /**
     * @Route("/addArticle", name="addArticle")
     */
    public function addArticle(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class,$article);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $message = $this->twilio->messages->create(
                '+21692881042', // Send text to this number
                array(
                    'from' => '+14454551924', // My Twilio phone number
                    'body' => 'Article ajouté avec succes  '
              )
            );
            $image = $form->get('image')->getData();
            foreach($image as $ima){
                $fichier = md5(uniqid()) . '.' . $ima->guessExtension();
                $ima->move(
                    $this->getParameter('img_directory'),
                    $fichier
                );
            }
            $em = $this->getDoctrine()->getManager();
            $article->setImage($fichier);
            $em->persist($article);//Add
            $em->flush();

            return $this->redirectToRoute('display_article');
        }
        return $this->render('article/createBlog.html.twig',['form'=>$form->createView()]);

    }

    /**
     * @Route("/removeArticle/{id}", name="supp_article")
     */
    public function deleteArticle(Article  $article): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($article);
        $em->flush();

        return $this->redirectToRoute('display_article');
    }
    /**
     * @Route("/modifArticle/{id}", name="modifArticle")
     */
    public function updateArticle(Request $request,$id): Response
    {
        $article = $this->getDoctrine()->getManager()->getRepository(Article::class)->find($id);
        $form = $this->createForm(ArticleType::class,$article);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();
            foreach($image as $ima){
                $fichier = md5(uniqid()) . '.' . $ima->guessExtension();
                $ima->move(
                    $this->getParameter('img_directory'),
                    $fichier
                );
            }
            $em = $this->getDoctrine()->getManager();
            $article->setImage($fichier);
            $em->flush();

            return $this->redirectToRoute('display_article');
        }
        return $this->render('article/updateArticle.html.twig',['form'=>$form->createView()]);
    }

    /**
     * @Route("/display", name="display")
     */
    public function displayArticleFront(): Response
    {
        $articles = $this->getDoctrine()->getManager()->getRepository(Article::class)->findAll();
        return $this->render('article/displayArticleFront.html.twig', [
            'articles'=>$articles
        ]);
    }

    /**
     * @Route("article/{id}", name="articleShow", methods={"GET", "POST"})
     */
    public function showArticle(Article $article, Request $request, ArticleRepository $articleRepository): Response
    {
        $review = new Review();
        $form = $this->createForm(ReviewType::class, $review);
        $form -> handleRequest($request);
        if($form -> isSubmitted() && $form -> isValid()){
            $review -> setArticle($article);
            $entityMannager = $this->getDoctrine() -> getManager();
            $entityMannager -> persist($review);
            $entityMannager -> flush();

            return $this->redirectToRoute("articleShow", ['id' => $article -> getId()]);
        }
        return $this->render('review/displayReviewFront.html.twig', [
            'article' => $article,
            'review' => $form -> createView(),
        ]);
    }

    /**
     * @Route("/pdf", name="pdf")
     */
    public  function displayPDF()
    {
        $options = new Options();
        $options->set('defaultFont', 'Courier');
        $articles = $this->getDoctrine()->getManager()->getRepository(Article::class)->findAll();
        $html= $this->render('article/pdf.html.twig', [
            'articles'=>$articles
        ]);
        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'landscape');
        $dompdf->render();
        $dompdf->stream();
    }

    /**
     * @Route("/orderTitre", name="orderTitre")
     */

    function orderByTitre(ArticleRepository $repository, Request $request,ArticleRepository $T){

        $article=$repository->orderByTitre();
        $formsearchI = $this->createForm(SearchType::class);
        $formsearchI->handleRequest($request);
        if ($formsearchI->isSubmitted()) {
            $titre = $formsearchI->getData();
            $TSearch = $T->search($titre['titre']);

            return $this->render("article/index.html.twig",
                array("articles" => $TSearch,"formsearch" => $formsearchI->createView())) ;
        }
        return $this->render("article/index.html.twig",array('articles' => $article,
            "formsearch" => $formsearchI->createView()));

    }

    /**
     * @Route("/orderDate", name="orderDate")
     */

    function orderByDate(ArticleRepository $repository, Request $request,ArticleRepository $T){

        $article=$repository->orderByDate();
        $formsearchI = $this->createForm(SearchType::class);
        $formsearchI->handleRequest($request);
        if ($formsearchI->isSubmitted()) {
            $titre = $formsearchI->getData();
            $TSearch = $T->search($titre['titre']);

            return $this->render("article/index.html.twig",
                array("articles" => $TSearch,"formsearch" => $formsearchI->createView())) ;
        }
        return $this->render("article/index.html.twig",array('articles' => $article,"formsearch" => $formsearchI->createView()));

    }

    /**
     * @Route("/display_article",name="display_article")
     */
    public function list(Request $request,ArticleRepository $T)
    {
        $articles=$this->getDoctrine()->getRepository(Article::class)->findAll();
        $formsearchI = $this->createForm(SearchType::class);
        $formsearchI->handleRequest($request);
        if ($formsearchI->isSubmitted()) {
            $titre = $formsearchI->getData();
            $TSearch = $T->search($titre['titre']);

            return $this->render("article/index.html.twig",
                array("articles" => $TSearch,"formsearch" => $formsearchI->createView())) ;
        }
        return $this->render("article/index.html.twig",array('articles'=>$articles,"formsearch" => $formsearchI->createView()));
    }
    public function getUserName(ArticleRepository $A)
    {
        $article=$A->orderByDate();
        return $this->render("review/displayReviewFront.html.twig",array('article' => $article));

    }
}

templates/article/createBlog.html.twig
{% extends 'admin/NavDash.html.twig' %}

    {% block body %}
        <div style="display:flex;align-items: center;justify-content: center;margin-top: 150px;">
            <!-- jquery validation -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 >Ajouter un article   </h3>
                    {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
                </div>
                <!-- /.card-header -->
                <!-- form start -->

                <form id="quickForm" novalidate="novalidate">
                    <div class="card-body">

                        <div class="form-group">
                            <label for="exampleInputEmail1">Titre de l'article</label>
                            {{ form_widget(form.titre,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.titre,{'attr':{'class':'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Description de l'article</label>
                            {{ form_widget(form.description,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.description,{'attr':{'class':'form-control'}}) }}
                        </div>

                    <label for="inputText" class="col-sm-4 col-form-label">Image</label>
                    <div class="col-sm-6">
                        {{ form_widget(form.image,{'attr':{'class':'form-control'}}) }}
                        {{ form_errors(form.image,{'attr':{'class':'form-control'}}) }}

                    </div>

                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        {{ form_widget(form.ajouter,{'attr':{'class':'btn btn-primary'}}) }}
                    </div>
                    {{ form_end(form) }}
                </form>
            </div>
            <!-- /.card -->
        </div>
    {% endblock %}

templates/article/displayArticleFront.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="{{asset("assets/css/bootstrap/bootstrap.css")}}">
    <link rel="stylesheet" href="{{asset("assets/css/jquery-ui.css")}}">
    <link rel="stylesheet" href="{{asset("assets/css/owl.carousel.min.css")}}">
    <link rel="stylesheet" href="{{asset("assets/css/owl.theme.default.min.css")}}">
    <link rel="stylesheet" href="{{asset("assets/css/owl.theme.default.min.css")}}">

    <link rel="stylesheet" href="{{asset("assets/css/jquery.fancybox.min.css")}}">

    <link rel="stylesheet" href="{{asset("assets/css/bootstrap-datepicker.css")}}">

    <link rel="stylesheet" href="{{asset("assets/fonts/flaticon/font/flaticon.css")}}">

    <link rel="stylesheet" href="{{asset("assets/css/aos.css")}}">

    <link rel="stylesheet" href="{{asset("assets/css/style.css")}}">



</head>

<body>

    <header class="site-navbar py-4" role="banner">
        <div class="container">
            <div class="d-flex align-items-center">
                <div class="site-logo">
                    <a href="index.html">
                       <!-- <img src="{{asset("adminAssets/img/tunikoora.png")}}" alt="Logo">-->
                    </a>
                </div>
                <div class="ml-auto">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                            <li><a href="{{path('app_home')}}" class="nav-link">Home</a></li>
                             <li><a href="display" class="nav-link">Blog</a></li>
                               <li><a href="{{path('app_prod_index')}}" class="nav-link">produit</a></li>
                                <li><a href="{{path('app_tck_index')}}" class="nav-link">ticket</a></li>
                           <li><a href="{{ path('view_joueur') }}" class="nav-link">Joueurs</a></li>
                           
                              
                                


                                      {% if is_granted('ROLE_ADMIN') %}
                  <li><a href="{{path('app_dashboard')}}" class="nav-link">Dash</a></li>
                  <li><a href="{{ path('view_joueur') }}" class="nav-link">Joueurs</a></li>

                  {% endif %}
                   {%if not app.user%}
                   <li><a href="{{ path('view_joueur') }}" class="nav-link">Joueurs</a></li>

                 <li><a href="{{path('app_register')}}" class="nav-link">Inscription</a></li>
                  <li><a href="{{path('app_login')}}" class="nav-link">Connexion</a></li>
                  {% else %}
                   <li{% if app.request.get('_route') == 'app_profile' %} class="active"{% endif %}><a href="{{path('app_profile')}}" class="nav-link">Profile</a></li>

                    <li><a href="{{path('app_message')}}" class="nav-link">Msg</a></li>
                 
                  <li><a href="{{path('app_logout')}}" class="nav-link">Déconnexion</a></li>

                  

                  {% endif %}
                           
                        </ul>
                    </nav>

                    <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right text-white"><span
                                class="icon-menu h3 text-white"></span></a>
                </div>
            </div>
        </div>

    </header>

    <div class="hero overlay" style="background-image: url('assets/images/bg_3.jpg');">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div >
                        <div >
                            <h3>Liste des articles</h3>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th style="color: #EEEEEE">Titre</th>
                            <th style="color: #EEEEEE">Description</th>
                            <th style="color: #EEEEEE">Image</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for a in articles %}
                            <tr>
                                <td style="color: #EEEEEE">{{ a.titre }}</td>
                                <td style="color: #EEEEEE">{{ a.description }}</td>
                                <td style="color: #EEEEEE"><img src="{{asset('/adminAssets/img/')~ a.image  }}" alt="" style="width: 200px; height: 150px"></td>
                                <td style="color: #EEEEEE"><a class="btn btn-light" href="{{ path('articleShow',{'id':a.id})}}" >View</a></td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
        </div>
    </div>




   

</div>
<!-- .site-wrap -->

<script src="{{asset("assets/js/jquery-3.3.1.min.js")}}"></script>
<script src="{{asset("assets/js/jquery-migrate-3.0.1.min.js")}}"></script>
<script src="{{asset("assets/js/jquery-ui.js")}}"></script>
<script src="{{asset("assets/js/popper.min.js")}}"></script>
<script src="{{asset("assets/js/bootstrap.min.js")}}"></script>
<script src="{{asset("assets/js/owl.carousel.min.js")}}"></script>
<script src="{{asset("assets/js/jquery.stellar.min.js")}}"></script>
<script src="{{asset("assets/js/jquery.countdown.min.js")}}"></script>
<script src="{{asset("assets/js/bootstrap-datepicker.min.js")}}"></script>
<script src="{{asset("assets/js/jquery.easing.1.3.js")}}"></script>
<script src="{{asset("assets/js/aos.js")}}"></script>
<script src="{{asset("assets/js/jquery.fancybox.min.js")}}"></script>
<script src="{{asset("jassets/s/jquery.sticky.js")}}"></script>
<script src="{{asset("assets/js/jquery.mb.YTPlayer.min.js")}}"></script>


<script src="js/main.js"></script>

</body>

</html>

templates/article/index.html.twig
{% extends 'admin/NavDash.html.twig' %}
{% block body %}

    <div class="row" style="display: flex;align-items: center;justify-content: center;margin-top: 20px;">

        <div class="col-lg-8">

            <div class="card">
                <div class="card-body">
                        <div align="Right">
                            {{ form_start(formsearch,{attr:{novalidate:'novalidate'}}) }}
                            {{ form_widget(formsearch.titre,{'attr':{'class':'form-control'}}) }}
                            {{ form_widget(formsearch.search,{'attr':{'class':'btn btn-primary'}}) }}
                            {{ form_end(formsearch) }}
                        </div>
                    <a href="{{ path('addArticle') }}"><i class="ri-arrow-left-circle-fill" style="font-size: 50px;"></i></a>
                    <h3>Liste des articles</h3>
                    <!-- Table with stripped rows -->
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Titre</th>
                            <th>Description</th>
                            <th>Image</th>
                            <th>Date de creation</th>
                            <th>Modifier</th>
                            <th>Supprimer</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for a in articles %}
                            <tr>
                                <td>{{ a.titre }}</td>
                                <td>{{ a.description }}</td>
                                <td><img src="{{asset('/adminAssets/img/')~ a.image  }}" alt="" style="width: 200px; height: 150px"></td>
                                <td>{{ a.date|date('d-m-Y')}}</td>
                                <td>
                                    <a class="btn btn-primary" href="{{ path('modifArticle',{'id':a.id}) }}">Modifier</a>
                                </td>
                                <td>
                                    <a class="btn btn-primary" href="{{ path('supp_article',{'id':a.id}) }}">Supprimer</a>
                                </td>

                            </tr>
                        {% endfor %}
                        <a class="btn btn-outline-secondary" href="{{ path('addArticle')}}">Ajouter un article</a>
                        <a class="btn btn-outline-secondary" href="{{ path('pdf')}}">Generation pdf</a>
                        <a class="btn btn-outline-secondary" href="{{ path('orderTitre')}}">Tri selon titre</a>
                        <a class="btn btn-outline-secondary" href="{{ path('orderDate')}}">Tri selon date</a>

                        </tbody>
                    </table>
                    </div>
            </div>

        </div>

    </div>
{% endblock %}

templates/article/pdf.html.twig
{% block body %}

                    <h3>BIENVENUE A TUNIKOORA</h3>
                    <h3>Liste des articles</h3>

                    <table border="1">
                        <thead>
                        <tr>
                            <th scope="col">TITRE</th>
                            <th scope="col">DESCRIPTION</th>
                            <th scope="col">Date de creation</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for a in articles %}
                            <tr>
                                <td>{{ a.titre }}</td>
                                <td>{{ a.description }}</td>
                                <td>{{ a.date|date('d-m-Y')}}</td>
                                </th>
                            </tr>

                        {% endfor %}


{% endblock %}

templates/article/updateArticle.html.twig
{% extends 'admin/NavDash.html.twig' %}
    {% block body %}
        <div style="display:flex;align-items: center;justify-content: center;margin-top: 150px;">

            <div class="card card-primary">
                <div class="card-header">
                    <h3 >Modifier un article </h3>
                    {{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
                </div>

                <form id="quickForm" novalidate="novalidate">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Titre de l'article</label>
                            {{ form_widget(form.titre,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.titre,{'attr':{'class':'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Description de l'article</label>
                            {{ form_widget(form.description,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.description,{'attr':{'class':'form-control'}}) }}
                        </div>

                        <label for="inputText" class="col-sm-4 col-form-label">Image</label>
                        <div class="col-sm-6">
                            {{ form_widget(form.image,{'attr':{'class':'form-control'}}) }}
                            {{ form_errors(form.image,{'attr':{'class':'form-control'}}) }}

                        </div>

                    </div>

                    <div class="card-footer">
                        {{ form_widget(form.ajouter,{'attr':{'class':'btn btn-primary'}}) }}
                    </div>
                    {{ form_end(form) }}
                </form>
            </div>
            <!-- /.card -->
        </div>
    {% endblock %}